// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function BuildSSHCommand(arg1) {
  return window['go']['main']['App']['BuildSSHCommand'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExportSafeConfig() {
  return window['go']['main']['App']['ExportSafeConfig']();
}

export function ParseSSHCommand(arg1) {
  return window['go']['main']['App']['ParseSSHCommand'](arg1);
}

export function PickPrivateKey() {
  return window['go']['main']['App']['PickPrivateKey']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function TrustHost(arg1) {
  return window['go']['main']['App']['TrustHost'](arg1);
}
