// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Bootstrap():Promise<main.BootstrapData>;

export function BrowserURL(arg1:string):Promise<main.OperationResult>;

export function BuildSSHCommand(arg1:main.TunnelProfile):Promise<string>;

export function CopyText(arg1:string):Promise<main.OperationResult>;

export function DeleteProfile(arg1:string):Promise<main.OperationResult>;

export function ExportSafeConfig():Promise<string>;

export function OpenProfileInBrowser(arg1:string):Promise<main.OperationResult>;

export function ParseSSHCommand(arg1:string):Promise<main.ParseCommandResult>;

export function PickPrivateKey():Promise<main.OperationResult>;

export function RegisterNativeHost(arg1:string):Promise<main.NativeHostRegistrationResult>;

export function SaveProfile(arg1:main.SaveProfileRequest):Promise<main.OperationResult>;

export function StartTunnel(arg1:main.StartTunnelRequest):Promise<main.OperationResult>;

export function StopTunnel(arg1:string):Promise<main.OperationResult>;

export function TrustHost(arg1:string):Promise<main.OperationResult>;
